# docker-compose.prod.yml 
version: '3.8'

services:
  backend:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/filter-app-backend:latest
    env_file:
      - ./.env
    restart: always

  frontend:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/filter-app-frontend:latest
    restart: always


  nginx:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/filter-app-nginx:latest
    ports:
      - "80:80" 
    restart: always
    depends_on:
      - backend
      - frontend

  media_worker: # New service for the media processing worker
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/filter-app-worker:latest
    env_file:
      - ./.env # Worker also needs SQS_QUEUE_URL, S3_BUCKET_NAME, AWS_REGION, LUT_DIRECTORY
    restart: always
